"""Reusable source assessments for the sports feasibility audit (v1, 2026-10-08).

``status`` reflects what this audit verified from this host on 2026-10-08:
  verified        - data endpoint answered with the expected payload
  verified_page   - page answered, but bulk data access was not exercised
  key_required    - endpoint exists but needs a (free) registration key; not exercised
  blocked         - HTTP 403 / bot challenge / connection reset from this host
  absent          - verified missing at the documented location (HTTP 404)
  paid            - requires a paid subscription; excluded by NO-PAID constraint
  unchecked       - not probed in this audit

``asof`` describes whether the data supports point-in-time reconstruction:
  derived  - only final results; pre-event features must be derived from earlier results
  dated    - publication is dated/versioned, so a past state can be read back
  closing  - pre-event numbers exist but are closing values (lookahead at earlier horizons)
  none     - current snapshot only; must be captured prospectively
"""

from __future__ import annotations

SOURCES: dict[str, dict] = {
    "kalshi_trade_api": dict(
        name="Kalshi Trade API v2 (public market data)", url="https://docs.kalshi.com/llms.txt",
        status="verified", role="markets, rules, settlement results, prices", asof="dated",
        depth="Sports series listed since 2021; most game-level series since 2025",
        limits="Unauthenticated reads throttled (HTTP 429 observed above ~8-10 req/s); tiered token "
               "budgets documented at docs.kalshi.com/getting_started/rate_limits",
        license="Kalshi API/developer terms (not legally reviewed)",
        notes="Settled markets before /historical/cutoff (market_settled_ts 2026-08-09) move to "
              "/historical/*; events and series stay on live endpoints."),
    "kalshi_candles_trades": dict(
        name="Kalshi candlesticks + trade prints", url="https://docs.kalshi.com/getting_started/historical_data.md",
        status="verified", role="contemporaneous prices (benchmark, execution)", asof="dated",
        depth="From market open; 1-min / 60-min / 1-day candles; individual trade prints",
        limits="No historical order-book depth endpoint; only top-of-book OHLC inside candles",
        license="Kalshi API terms", notes="See price probe for per-family verification."),
    "kalshi_milestones": dict(
        name="Kalshi milestones + structured targets", url="https://docs.kalshi.com/getting_started/targets_and_milestones.md",
        status="verified", role="event registry, team/player IDs, external source IDs", asof="none",
        depth="154,335 sports milestones (start dates 2025-2027); 280,988 structured targets (all categories)",
        limits="Paginated (500 / 2000 per page)", license="Kalshi API terms",
        notes="details include last-5 results and injury notes, but are overwritten in place "
              "(last_updated_ts); usable as-of only if captured prospectively."),
    "kalshi_live_data": dict(
        name="Kalshi live data / game stats", url="https://docs.kalshi.com/api-reference/live-data/get-game-stats.md",
        status="verified", role="final scores, winners, method of victory, leaderboards, play-by-play",
        asof="derived", depth="Milestones from 2025; PBP for NFL, NCAAF, NBA, NCAAB, WNBA, soccer, NHL, MLB",
        limits="Same Kalshi read budget", license="Kalshi API terms",
        notes="Final state only for completed events; independent cross-check of Kalshi settlement."),
    "espn_site_api": dict(
        name="ESPN site API (unofficial JSON)", url="https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard?dates=20240115",
        status="verified", role="schedules, results, box scores, leaderboards (multi-sport)", asof="derived",
        depth="Major US leagues ~2000s+; varies by sport/league", limits="Undocumented; no published quota",
        license="Undocumented API under Disney terms of use (disneytermsofuse.com); research caching only",
        notes="Past-game odds field absent/null in NBA/NFL/MLB/NHL/EPL samples - not an odds history source."),
    "nba_stats": dict(
        name="stats.nba.com / cdn.nba.com", url="https://stats.nba.com/stats/scoreboardv2",
        status="blocked", role="official NBA/WNBA stats", asof="derived", depth="1946+ (claimed)",
        limits="Connection reset (stats) and HTTP 403 (cdn) from this host", license="NBA terms of use",
        notes="Use ESPN or Kalshi live data instead."),
    "sports_reference": dict(
        name="Sports Reference (Basketball/Baseball/Pro-Football/Hockey-Reference, FBref)",
        url="https://www.sports-reference.com/bot-traffic.html", status="verified_page",
        role="historical stats, awards voting, draft history", asof="derived", depth="Decades",
        limits="20 req/min (10 for FBref); FBref returned a Cloudflare challenge (403)",
        license="ToU forbids automated access that harms the site and building competing databases",
        notes="Manual/low-volume reference only; not a pipeline source."),
    "barttorvik": dict(
        name="Barttorvik T-Rank", url="https://barttorvik.com/2024_team_results.json", status="verified",
        role="NCAA basketball team ratings/results", asof="dated",
        depth="2008+ (site claim)", limits="Unpublished", license="Unpublished terms",
        notes="Date-filtered ratings are offered on-site; as-of fidelity not verified in this audit."),
    "kenpom": dict(name="KenPom", url="https://kenpom.com/", status="paid", role="NCAA ratings (Kalshi KenPom markets settle on it)",
                   asof="dated", depth="2002+", limits="Subscription", license="Paid",
                   notes="Blocks KenPom-ranking markets under the no-paid constraint."),
    "euroleague_api": dict(name="EuroLeague live API", url="https://api-live.euroleague.net/v1/results?seasonCode=E2023",
                           status="verified", role="EuroLeague results", asof="derived", depth="2000s+",
                           limits="Unpublished", license="Unpublished terms", notes=""),
    "ncaa_casablanca": dict(name="NCAA.com scoreboard JSON (unofficial)",
                            url="https://data.ncaa.com/casablanca/scoreboard/basketball-men/d1/2024/01/20/scoreboard.json",
                            status="verified", role="NCAA results (basketball, volleyball, lacrosse, ...)",
                            asof="derived", depth="Several seasons (varies)", limits="Unpublished",
                            license="NCAA terms (unofficial endpoint)", notes=""),
    "mlb_statsapi": dict(name="MLB Stats API", url="https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=2024-07-01",
                         status="verified", role="MLB schedules, results, box scores, probable pitchers",
                         asof="derived", depth="Verified back to 2005 schedules",
                         limits="Unpublished",
                         license="MLBAM notice: individual, non-commercial, non-bulk use only (gdx.mlb.com/components/copyright.txt)",
                         notes="probablePitcher for past games reflects the actual starter, not the as-of announcement."),
    "retrosheet": dict(name="Retrosheet", url="https://www.retrosheet.org/gamelogs/index.html", status="verified",
                       role="MLB game logs/event files", asof="derived", depth="1871+ (released after season)",
                       limits="Bulk files", license="Free for any use with required attribution notice (retrosheet.org/notice.txt)",
                       notes=""),
    "baseball_savant": dict(name="Baseball Savant (Statcast CSV)", url="https://baseballsavant.mlb.com/statcast_search",
                            status="verified", role="pitch-level MLB data", asof="derived", depth="2008+ (pitch tracking 2015+)",
                            limits="Query row caps", license="MLBAM terms", notes=""),
    "npb_kbo_official": dict(name="NPB / KBO official sites", url="https://npb.jp/bis/eng/2024/games/",
                             status="verified_page", role="NPB/KBO results (HTML)", asof="derived",
                             depth="Multi-season HTML", limits="HTML scraping", license="Site terms",
                             notes="ESPN coverage of NPB/KBO not verified."),
    "nflverse": dict(name="nflverse (nfldata games.csv, nflverse-data releases)",
                     url="https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv",
                     status="verified", role="NFL schedules/results + closing spread/total/moneyline + PBP",
                     asof="closing", depth="1999-2026 games; lines present through 2026",
                     limits="GitHub raw/release downloads",
                     license="nflverse-data repo CC-BY-4.0; nfldata repo has no LICENSE file (GitHub API license=null)",
                     notes="Lines are closing values without capture timestamps; weather fields are game-time."),
    "cfbd": dict(name="CollegeFootballData API", url="https://api.collegefootballdata.com/games?year=2024&week=1",
                 status="key_required", role="NCAAF results, historical betting lines", asof="closing",
                 depth="Decades of results; lines ~2013+ (provider claim)", limits="Free key tier quotas",
                 license="Provider terms (not reviewed)", notes="HTTP 401 without key on 2026-10-08."),
    "cfl_api": dict(name="CFL API", url="https://api.cfl.ca/v1/games/2024", status="blocked", role="CFL results",
                    asof="derived", depth="", limits="Key required; connection failed from this host",
                    license="CFL terms", notes="ESPN does not obviously cover CFL; not verified."),
    "nhl_api": dict(name="NHL web API (api-web.nhle.com)", url="https://api-web.nhle.com/v1/score/2024-01-15",
                    status="verified", role="NHL schedules, results, boxscores", asof="derived",
                    depth="Verified back to 2010", limits="Unpublished", license="NHL terms of service", notes=""),
    "moneypuck": dict(name="MoneyPuck data", url="https://moneypuck.com/data.htm", status="verified_page",
                      role="NHL shot/xG data", asof="derived", depth="2008+", limits="Bulk CSV",
                      license="Terms not verified", notes=""),
    "football_data_co_uk": dict(name="football-data.co.uk", url="https://www.football-data.co.uk/mmz4281/2324/E0.csv",
                                status="verified", role="soccer results + pre-closing and closing 1X2, O/U 2.5, Asian handicap odds",
                                asof="closing", depth="1993+ (EPL); ~22 European divisions + extra leagues (e.g. BRA)",
                                limits="Static CSVs", license="Free use (site); terms not legally reviewed",
                                notes="Pre-closing odds captured at a fixed weekday time; closing odds are lookahead before kickoff."),
    "football_data_org": dict(name="football-data.org API", url="https://api.football-data.org/v4/competitions/PL/matches",
                              status="key_required", role="soccer fixtures/results", asof="derived",
                              depth="Free tier: limited competitions", limits="10 req/min free tier",
                              license="Provider terms", notes="HTTP 403 without key."),
    "clubelo": dict(name="ClubElo API", url="http://api.clubelo.com/2024-01-15", status="blocked",
                    role="dated club Elo ratings", asof="dated", depth="1940s+ (site claim)",
                    limits="HTTP 502 on 2026-10-08 (two attempts)", license="Unpublished",
                    notes="Could not be checked; re-test before use."),
    "eloratings_net": dict(name="World Football Elo Ratings", url="https://www.eloratings.net/World.tsv",
                           status="verified", role="national-team Elo", asof="derived", depth="1872+",
                           limits="Static TSV", license="Unpublished", notes="Current table; history via per-team pages."),
    "openfootball": dict(name="openfootball football.json", url="https://raw.githubusercontent.com/openfootball/football.json/master/2023-24/en.1.json",
                         status="verified", role="soccer fixtures/results", asof="derived", depth="Multi-season, major leagues",
                         limits="GitHub raw", license="CC0-1.0 (GitHub API)", notes=""),
    "understat": dict(name="Understat", url="https://understat.com/league/EPL/2023", status="verified_page",
                      role="soccer xG (top 6 leagues)", asof="derived", depth="2014+", limits="HTML-embedded JSON",
                      license="Terms not verified", notes=""),
    "sackmann_tennis": dict(name="Jeff Sackmann tennis_atp / tennis_wta", url="https://github.com/JeffSackmann/tennis_atp",
                            status="absent", role="ATP/WTA match results + rankings", asof="derived",
                            depth="", limits="", license="Was CC BY-NC-SA 4.0",
                            notes="GitHub API 404 for both repos on 2026-10-08; account lists only "
                                  "tennis_MatchChartingProject. Third-party mirrors exist with unclear provenance."),
    "tennis_data_co_uk": dict(name="tennis-data.co.uk", url="http://www.tennis-data.co.uk/2024/2024.xlsx",
                              status="blocked", role="ATP/WTA results + closing odds", asof="closing",
                              depth="2000+ (site claim)", limits="HTTP 403 from this host (default and browser UA)",
                              license="Unverified", notes="Could not be checked."),
    "datagolf": dict(name="Data Golf API", url="https://datagolf.com/api-access", status="paid",
                     role="strokes-gained, predictions, historical odds", asof="dated", depth="",
                     limits="Paid", license="Paid", notes="Excluded."),
    "owgr": dict(name="Official World Golf Ranking", url="https://www.owgr.com/current-world-ranking",
                 status="verified_page", role="weekly golf rankings", asof="dated", depth="Weekly archive (site)",
                 limits="HTML/JS app", license="Site terms", notes="Archive access path not exercised."),
    "ufcstats": dict(name="UFCStats", url="http://ufcstats.com/statistics/events/completed?page=all",
                     status="blocked", role="UFC fight results/stats", asof="derived", depth="1993+",
                     limits="Returned a 3 KB 'Loading' JS-challenge page", license="Site terms",
                     notes="ESPN MMA scoreboard verified as alternative for results."),
    "boxrec": dict(name="BoxRec", url="https://boxrec.com/en/schedule", status="blocked",
                   role="boxing records", asof="derived", depth="", limits="Cloudflare 403",
                   license="Login-gated; terms restrict scraping", notes=""),
    "jolpica_f1": dict(name="Jolpica-F1 (Ergast successor)", url="https://api.jolpi.ca/ergast/f1/2024/results.json",
                       status="verified", role="F1 results, qualifying, standings", asof="derived",
                       depth="1950+ (1990 verified)", limits="Documented burst/sustained limits",
                       license="See jolpica-f1 repository", notes=""),
    "openf1": dict(name="OpenF1", url="https://api.openf1.org/v1/sessions?year=2024&session_name=Race",
                   status="verified", role="F1 sessions, laps, timing", asof="derived", depth="2023+",
                   limits="Free historical tier", license="Provider terms", notes=""),
    "nascar_cacher": dict(name="NASCAR cacher JSON (unofficial)", url="https://cf.nascar.com/cacher/2024/1/race_list_basic.json",
                          status="verified", role="NASCAR schedules/results", asof="derived", depth="Multi-season",
                          limits="Unofficial", license="NASCAR terms", notes=""),
    "motogp_pulselive": dict(name="MotoGP Pulselive API (unofficial)", url="https://api.motogp.pulselive.com/motogp/v1/results/seasons",
                             status="verified", role="MotoGP results", asof="derived", depth="1949+ seasons list",
                             limits="Unofficial", license="Dorna terms", notes=""),
    "cricsheet": dict(name="Cricsheet", url="https://cricsheet.org/downloads/", status="verified",
                      role="ball-by-ball cricket results", asof="derived", depth="2000s+ internationals, IPL, T20 leagues",
                      limits="Bulk zip", license="ODC-By (JSON/registers); CC-BY 4.0 (XML)", notes=""),
    "opendota": dict(name="OpenDota API", url="https://api.opendota.com/api/proMatches", status="verified",
                     role="Dota 2 pro match results", asof="derived", depth="2010s+", limits="Free tier rate limits",
                     license="Provider terms", notes=""),
    "liquipedia": dict(name="Liquipedia MediaWiki/LPDB API", url="https://liquipedia.net/api-terms-of-use",
                       status="verified", role="esports results (CS2, LoL, Valorant, Dota, R6, OW)", asof="derived",
                       depth="Multi-year", limits="LPDB requires approval, 60 req/hour; no automated HTML access",
                       license="CC-BY-SA 3.0 with attribution", notes=""),
    "oracles_elixir": dict(name="Oracle's Elixir LoL data", url="https://oracleselixir.com/tools/downloads",
                           status="verified_page", role="LoL pro match data", asof="derived", depth="2014+",
                           limits="Google Drive downloads", license="Site terms", notes=""),
    "hltv": dict(name="HLTV", url="https://www.hltv.org/results", status="verified_page", role="CS2 results",
                 asof="derived", depth="2000s+", limits="HTML; aggressive anti-bot reported", license="Site terms",
                 notes="Kalshi CS2 series cite HLTV as a source agency."),
    "fide": dict(name="FIDE rating lists", url="https://ratings.fide.com/download_lists.phtml", status="verified_page",
                 role="monthly chess ratings", asof="dated", depth="Monthly lists (archive)", limits="Bulk zip",
                 license="FIDE terms", notes="Archive file links not parsed in this audit."),
    "chesscom_lichess": dict(name="Chess.com / Lichess public APIs", url="https://api.chess.com/pub/player/hikaru/stats",
                             status="verified", role="online ratings/results (Titled Tuesday)", asof="derived",
                             depth="Multi-year", limits="Public API etiquette", license="Provider terms",
                             notes="Tournament endpoint guess returned 403; tournament history path unverified."),
    "squiggle": dict(name="Squiggle AFL API", url="https://api.squiggle.com.au/?q=games;year=2024;round=1",
                     status="verified", role="AFL results + model tips", asof="dated", depth="2017+ tips; results longer",
                     limits="User-Agent required", license="Provider terms", notes="Tips carry 'updated' timestamps."),
    "afltables": dict(name="AFL Tables", url="https://afltables.com/afl/seas/2024.html", status="verified_page",
                      role="AFL history", asof="derived", depth="1897+", limits="HTML", license="Site terms", notes=""),
    "html_only_misc": dict(name="HTML-only results sites (dartsdatabase, procyclingstats, WTT, Olympedia, World Athletics, SailGP, NYRR)",
                           url="https://www.dartsdatabase.co.uk/", status="verified_page", role="results",
                           asof="derived", depth="Varies", limits="Scraping required", license="Per-site terms",
                           notes="Feasible for small samples only."),
    "sportsoddshistory": dict(name="SportsOddsHistory", url="https://www.sportsoddshistory.com/nba-main/",
                              status="verified_page", role="historical futures/award odds tables", asof="dated",
                              depth="Decades (site)", limits="HTML", license="Site terms",
                              notes="Opening/closing futures snapshots; not intraday."),
    "sbr_archive": dict(name="SportsbookReviewsOnline odds archive", url="https://www.sportsbookreviewsonline.com/scoresoddsarchives/nba/nbaoddsarchives.htm",
                        status="verified_page", role="historical game odds (NBA/NFL/MLB/NHL/NCAA)", asof="closing",
                        depth="Historic seasons", limits="No downloadable file links found on 2026-10-08",
                        license="Site terms", notes="Treat as unavailable until files are located."),
    "thesportsdb": dict(name="TheSportsDB", url="https://www.thesportsdb.com/api/v1/json/3/eventsday.php?d=2024-01-15&s=Soccer",
                        status="verified", role="crowd-sourced schedules/results", asof="derived", depth="Varies",
                        limits="Free test key; paid tiers", license="Provider terms", notes="Quality varies; fallback only."),
}

# Per-sport assessment. Keys refer to SOURCES. "inputs" lists pre-event inputs and how
# (if at all) they can be reconstructed as-of from free sources.
SPORTS: dict[str, dict] = {
    "Basketball": dict(
        results=["espn_site_api", "kalshi_live_data", "ncaa_casablanca", "euroleague_api"],
        results_status="free",
        player_stats="free (ESPN box scores; Kalshi game_stats PBP for NBA/WNBA/NCAAB)",
        odds_history="none verified free (SBR files not found; ESPN no past odds)",
        inputs="Ratings derivable from results (as-of exact); rest/travel from schedules; injuries/"
               "lineups NOT reconstructable (Kalshi milestone injury notes are overwritten)",
        notes="stats.nba.com blocked from this host; KenPom paid; international leagues via ESPN/Kalshi live data only."),
    "Football": dict(
        results=["nflverse", "espn_site_api", "kalshi_live_data", "cfbd"],
        results_status="free",
        player_stats="free (nflverse PBP/player stats CC-BY-4.0; ESPN box scores)",
        odds_history="NFL closing spread/total/ML in nflverse (closing only); NCAAF via CFBD (free key, not exercised)",
        inputs="Ratings from results; closing lines usable only as a market-proxy at close; QB starter "
               "and injury status not reconstructable as-of",
        notes="CFL source blocked; Kalshi CFL coverage small."),
    "Baseball": dict(
        results=["mlb_statsapi", "retrosheet", "espn_site_api", "kalshi_live_data"],
        results_status="free (MLBAM non-commercial/non-bulk notice)",
        player_stats="free (Stats API box scores, Statcast)",
        odds_history="none verified free",
        inputs="Ratings from results; probable starting pitchers are the key input and are NOT "
               "reconstructable as-of (historical feed shows the actual starter)",
        notes="NPB/KBO/LMB require HTML scraping or Kalshi live data."),
    "Hockey": dict(
        results=["nhl_api", "espn_site_api", "kalshi_live_data", "moneypuck"],
        results_status="free",
        player_stats="free (NHL API boxscores)",
        odds_history="none verified free",
        inputs="Ratings from results; starting goalie not reconstructable as-of",
        notes="European leagues (KHL, SHL, Liiga, DEL, Extraliga), AHL and NCAA via Kalshi live data / ESPN only."),
    "Soccer": dict(
        results=["football_data_co_uk", "openfootball", "espn_site_api", "kalshi_live_data"],
        results_status="free",
        player_stats="partial (goalscorers via ESPN/Kalshi PBP; no free bulk lineups)",
        odds_history="football-data.co.uk pre-closing + closing 1X2/OU2.5/AH for ~22+ leagues",
        inputs="Ratings/Poisson strengths from results (as-of exact); dated Elo (ClubElo, unreachable on audit day); "
               "lineups not reconstructable",
        notes="Kalshi lists ~200 soccer competitions; many minor leagues lack a free bulk results source beyond Kalshi live data."),
    "Tennis": dict(
        results=["espn_site_api", "kalshi_live_data"],
        results_status="partial (main tours via ESPN; Challenger/ITF only via Kalshi live data)",
        player_stats="n/a",
        odds_history="none verified (tennis-data.co.uk blocked)",
        inputs="Player Elo derivable from results; rankings as-of require archive (Sackmann repos absent)",
        notes="Largest Kalshi milestone count (65k tennis tournaments); Challenger/ITF depth is the main gap."),
    "Golf": dict(
        results=["espn_site_api", "kalshi_live_data", "owgr"],
        results_status="free (leaderboards)",
        player_stats="round scores via ESPN leaderboards",
        odds_history="none free (Data Golf paid)",
        inputs="Field strength from prior finishes (derivable); weekly OWGR is dated",
        notes="Strokes-gained requires paid data."),
    "Motorsport": dict(
        results=["jolpica_f1", "openf1", "nascar_cacher", "motogp_pulselive", "kalshi_live_data"],
        results_status="free",
        player_stats="laps/qualifying (OpenF1 2023+)",
        odds_history="none free",
        inputs="Qualifying/grid is public before the race and reconstructable from timed results",
        notes=""),
    "MMA": dict(
        results=["espn_site_api", "kalshi_live_data"],
        results_status="free (ESPN, Kalshi live data); UFCStats blocked",
        player_stats="limited",
        odds_history="none free",
        inputs="Fighter records derivable; late replacements not reconstructable",
        notes="Small independent sample per year."),
    "Boxing": dict(results=["espn_site_api", "kalshi_live_data"], results_status="partial",
                   player_stats="n/a", odds_history="none free",
                   inputs="BoxRec blocked; records sparse", notes="Few events."),
    "Cricket": dict(results=["cricsheet", "kalshi_live_data"], results_status="free",
                    player_stats="ball-by-ball (Cricsheet)", odds_history="none free",
                    inputs="Team ratings derivable; toss/XI announced shortly before start - not reconstructable",
                    notes=""),
    "Esports": dict(results=["liquipedia", "opendota", "oracles_elixir", "kalshi_live_data"],
                    results_status="free with rate-limit/approval constraints",
                    player_stats="game-specific", odds_history="none free",
                    inputs="Team ratings derivable; roster changes partially in Liquipedia history",
                    notes="HLTV is a Kalshi source agency for CS2 but is HTML-only."),
    "Chess": dict(results=["fide", "chesscom_lichess", "kalshi_live_data"], results_status="partial",
                  player_stats="n/a", odds_history="none", inputs="Monthly FIDE lists are dated (as-of by month)",
                  notes=""),
    "Table Tennis": dict(results=["kalshi_live_data", "html_only_misc"], results_status="Kalshi-only in practice",
                         player_stats="n/a", odds_history="none",
                         inputs="Player ratings derivable only from Kalshi-observed results",
                         notes="TT Elite Series has ~11k Kalshi events; no verified free bulk results source."),
    "Darts": dict(results=["kalshi_live_data", "html_only_misc"], results_status="partial (HTML)",
                  player_stats="n/a", odds_history="none", inputs="Derivable from results", notes=""),
    "Rugby": dict(results=["espn_site_api", "kalshi_live_data"], results_status="partial",
                  player_stats="n/a", odds_history="none", inputs="Derivable from results", notes=""),
    "Volleyball": dict(results=["ncaa_casablanca", "kalshi_live_data"], results_status="free",
                       player_stats="n/a", odds_history="none", inputs="Derivable from results", notes=""),
    "Lacrosse": dict(results=["ncaa_casablanca", "espn_site_api", "kalshi_live_data"], results_status="free",
                     player_stats="n/a", odds_history="none", inputs="Derivable from results", notes=""),
    "Aussie Rules": dict(results=["squiggle", "afltables", "kalshi_live_data"], results_status="free",
                         player_stats="n/a", odds_history="none (Squiggle tips are dated model forecasts)",
                         inputs="Derivable from results; Squiggle aggregate tips are dated", notes=""),
    "Olympics": dict(results=["html_only_misc", "kalshi_live_data"], results_status="partial (HTML)",
                     player_stats="n/a", odds_history="none", inputs="Event-specific; quadrennial sample",
                     notes="Episodic."),
}

DEFAULT_SPORT = dict(results=["kalshi_live_data", "html_only_misc"], results_status="unverified",
                     player_stats="n/a", odds_history="none", inputs="Not assessed beyond Kalshi data",
                     notes="Long-tail sport/tag; not assessed individually.")


def sport_assessment(sport: str) -> dict:
    return SPORTS.get(sport, DEFAULT_SPORT)
